"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.username = exports.recipient = exports.path = exports.port = exports.password = exports.name = exports.mimetype = exports.id = exports.host = exports.filename = exports.email = void 0;
const email_schema_1 = require("./email.schema");
Object.defineProperty(exports, "email", { enumerable: true, get: function () { return email_schema_1.email; } });
const filename_schema_1 = require("./filename.schema");
Object.defineProperty(exports, "filename", { enumerable: true, get: function () { return filename_schema_1.filename; } });
const host_schema_1 = require("./host.schema");
Object.defineProperty(exports, "host", { enumerable: true, get: function () { return host_schema_1.host; } });
const id_schema_1 = require("./id.schema");
Object.defineProperty(exports, "id", { enumerable: true, get: function () { return id_schema_1.id; } });
const mimetype_schema_1 = require("./mimetype.schema");
Object.defineProperty(exports, "mimetype", { enumerable: true, get: function () { return mimetype_schema_1.mimetype; } });
const name_schema_1 = require("./name.schema");
Object.defineProperty(exports, "name", { enumerable: true, get: function () { return name_schema_1.name; } });
const password_schema_1 = require("./password.schema");
Object.defineProperty(exports, "password", { enumerable: true, get: function () { return password_schema_1.password; } });
const port_schema_1 = require("./port.schema");
Object.defineProperty(exports, "port", { enumerable: true, get: function () { return port_schema_1.port; } });
const path_schema_1 = require("./path.schema");
Object.defineProperty(exports, "path", { enumerable: true, get: function () { return path_schema_1.path; } });
const recipient_schema_1 = require("./recipient.schema");
Object.defineProperty(exports, "recipient", { enumerable: true, get: function () { return recipient_schema_1.recipient; } });
const username_schema_1 = require("./username.schema");
Object.defineProperty(exports, "username", { enumerable: true, get: function () { return username_schema_1.username; } });
