import { email } from './email.schema';
import { filename } from './filename.schema';
import { host } from './host.schema';
import { id } from './id.schema';
import { mimetype } from './mimetype.schema';
import { name } from './name.schema';
import { password } from './password.schema';
import { port } from './port.schema';
import { path } from './path.schema';
import { recipient } from './recipient.schema';
import { username } from './username.schema';
export { email, filename, host, id, mimetype, name, password, port, path, recipient, username };
