export { Cliam } from './classes/cliam.class';
export { SendingResponse } from './classes/sending-response.class';
export { SendingError } from './classes/sending-error.class';
export { EVENT } from './types/enums/event.enum';
export { PROVIDER } from './types/enums/provider.enum';
export { ATTACHMENT_MIME_TYPE } from './types/enums/attachment-mime-type.enum';
export { ATTACHMENT_DISPOSITION } from './types/enums/attachment-disposition.enum';
export { BUFFER_MIME_TYPE } from './types/enums/buffer-mime-type.enum';

export type { IClientConfiguration } from './classes/client-configuration.class';
export type { ITransporterConfiguration } from './transporters/ITransporterConfiguration.interface';
export type { Event } from './types/types/event.type';
export type { Provider } from './types/types/provider.type';
export type { IPayload } from './types/interfaces/IPayload.interface';
export type { IAddressable } from './types/interfaces/addresses/IAddressable.interface';
export type { IAttachment } from './types/interfaces/IAttachment.interface';
export type { IBuffer } from './types/interfaces/IBuffer.interface';
export type { IPlaceholder } from './types/interfaces/IPlaceholder.interface';
export type { ISendingResponse } from './types/interfaces/ISendingResponse.interface';
export type { ISendingError } from './types/interfaces/ISendingError.interface';
