name: Build
on:
  push:
    branches: [ dev, main, hotfix/*, feature/*, release/* ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cache dependencies
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: '**/node_modules'
          key: bun-modules-${{ hashfiles('**/bun.lockb') }}
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@2b176a6e02983d9ed668db3c687439eb49fe611a # v2.2.0
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Build
        run: bun run build

  test:
    runs-on: ubuntu-latest
    env:
      RUNNER: github
      NODE_ENV: dev
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@2b176a6e02983d9ed668db3c687439eb49fe611a # v2.2.0
        with:
          bun-version: latest
      - name: Install NPM dependencies
        run: bun install
      - name: Copy .env + cliamrc files
        run: cp .local.env .env && cp ./test/fixtures/cliamrc.js ./.cliamrc.js
      - name: Execute units tests
        run: bun run ci:test
      - name: Publish coverage to coveralls.io
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: ./reports/coverage/lcov.info
      - name: Publish coverage to Qlty
        uses: qltysh/qlty-action/coverage@a19242102d17e497f437d7466aa01b528537e899 # v2.2.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: ./reports/coverage/lcov.info
