name: Release
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      RUNNER: github
      NODE_ENV: dev
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install NPM dependencies
        run: bun install
      - name: Lint
        run: bun run lint
      - name: Build
        run: bun run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/
            package.json
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      RUNNER: github
      NODE_ENV: dev
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Bun environment
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install NPM dependencies
        run: bun install
      - name: Copy .env file
        run: cp .local.env .env
      - name: Copy .cliamrc.js file
        run: cp ./test/fixtures/cliamrc.js ./.cliamrc.js
      - name: Execute units tests
        run: bun run ci:test
      - name: Publish to coveralls.io
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./reports/coverage/lcov.info
  release:
    name: Release on Github
    runs-on: ubuntu-latest
    needs: [ build, test ]
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Create release
        uses: konfer-be/action-create-release-from-tag@v1.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    name: Publish on NPM
    runs-on: ubuntu-latest
    needs: [ release ]
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish package on NPM registery
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
